### ISSUE TITLE
Isn't skipping when using shift+tab

### ISSUE THREAD

**Issue by adam-lynch** [joelpurra/skipontab#5]
- Go to http://codepen.io/adam-lynch/pen/doNOZJ
- Click `hello`
- Press tab. It's skipped (`hello 3` is focused).
- Press shift+tab. It's not skipped (`hello 2` is focused).

The pen uses jQuery 2.1.3.

**Comment by joelpurra** [comment]
@adam-lynch: from the docs:

> Skipped fields can still be navigated to by keyboard; once skipped and focusing the next form field, use <kbd>shift</kbd>-<kbd>tab</kbd> to step back.

It's actually a feature =)

If you really never want to be able to focus the field using the keyboard, `tabindex="-1"` sounds like the way to go -- but [I wouldn't recommend it](https://github.com/joelpurra/skipontab/wiki/SkipOnTab-versus-tabindex) as SkipOnTab solves exactly that problem.

**Comment by adam-lynch** [comment]
Ok, I misread that. 

Not sure this warrants dropping SkipOnTab and going back to tabindex. Could it be an option? My use case is that I don't want any tabbable elements in hidden elements to be tabbed onto. For example the user could open a full screen form (in front of the existing elements) and I don't want them to be able to tab onto the elements underneath.

I want to use SkipOnTab because I don't want to have to add `tabindex="-1"` to every tabbable element when this full-screen form is opened and remove them when it's closed. This full-screen form is just one example by the way.

**Comment by joelpurra** [comment]
@adam-lynch: if you by hiding mean obscuring (not `display: none;`), then yes, you'd need to disable focusing in another way. Unfortunately SkipOnTab isn't made to -- and shouldn't -- completely block access to inputs etcetera. It's better to do one thing and do it well, and that is a different feature.

Last time I had this problem I used another plugin which did some tricks to avoid focusing -- but it was a year ago so can't recall.

Have thought of creating something similar to SkipOnTab which jumps to an arbitrary input like `data-next-focus="#other-input-selector"`, but haven't yet. This would accompany emulatetab, skipontab and plusastab nicely, but it's not in my planning at the moment -- I'll wait until I have the need again.

**Comment by adam-lynch** [comment]
I started going down the route of creating my own module which does what SkipOnTab does (kind of) but that handles clicks on stuff in "ignored" containers, etc. etc. I was trying to do too much clearly and it was tough going anyway, then I discovered this module. This solves everything except this one thing. 

One last try: my code also runs in NW.js (formely node-webkit), i.e. the desktop, so I have stuff like window controls which the user shouldn't ever be able to tab onto. I've another idea to solve it: you allow skipping via API and data-attributes, what if you also had events? So someone could do: 

```javascript
$('a').on('prefocus.skipOnTab', function(e){
    // maybe check if e.target is in a certain element or has a certain class, etc. etc.
    if(doACheck){ 
        e.preventDefault(); // skips it
    }
});
```

So this would just users even more control in a typically JavaScripty way (and also give me what I want :stuck_out_tongue:).

**Comment by joelpurra** [comment]
@adam-lynch: sorry, blocking focus is a new plugin, not a skipontab feature.

That kind of event is just the same as what skipontab is doing with the `focusin` event but with custom reasons for `event.preventDefault(); event.stopPropagation(); event.stopImmediatePropagation(); return false;` -- but I see no reason to delegate it to a new, wrapped event. It isn't even *skipping* a field, it's *blocking* focus. As you can see, it can easily be done by a new plugin implementing these custom rules. I wouldn't go the event/rules route though, but use attributes as they can be made to apply to an entire hierarchy. Skipontab is BSD licensed (copyright PTS), and would make a nice base with for example `data-` attribute features already in place =)

If you have fields which should *"never"* be focused, it sounds like you should use `display: none;` or `tabindex="-1"` -- or perhaps wrap them in `<script>` tags if they're templates.

**Comment by adam-lynch** [comment]
> It isn't even skipping a field, it's blocking focus. 

I meant it to skip i.e. if you did `e.preventDefault()`, the module would catch it with `event.isDefaultPrevented()` and then skip onto the next thing.

>If you have fields which should "never" be focused, it sounds like you should use display: none; or tabindex="-1" -- or perhaps wrap them in `<script>` tags if they're templates.

I'll end up living with this I guess instead of creating a new module and using `tabindex="-1"` on my window controls. `display: none;` is rarely the right solution I think because someone might need to show/hide stuff in their own way for various reasons (i.e. rendering performance on mobile, etc.) and in my own case the full-screen form has a semi-transparent background so we can't hide the elements behind at all.

**Comment by joelpurra** [comment]
@adam-lynch: ah. That is closer to what skipontab does, except you want in in reverse as well. I see that it's an easy fix to ignore reverse tabbing if you also add `data-skip-on-tab="false"` (or equivalent) to non-modal (and similar) inputs, but I think it's an improper solution for this plugin. There's room for the feature, but not in this plugin -- a completely different solution or something like `data-next-focus="#other-input-selector"` would work better.

Haven't tested mobile rendering performance regarding hiding parts of forms (or "outside" forms), so can't really comment on it. Here are some non-plugin solutions for modals though:
https://stackoverflow.com/questions/16554347/keeping-the-tab-focus-inside-a-jquery-dialog
https://stackoverflow.com/questions/14572084/keep-tabbing-within-modal-pane-only
